### ISSUE TITLE
CMD/Black Window and Double instance of a player with livestreamer.

### ISSUE THREAD

**Issue by dragons4life** [u8sand/Baka-MPlayer#108]
Currently using Windows 8.1

Normally when opening the player a CMD/Black Window will pop out and never close unless i do it myself manually, can this be closed automatically or do i have to do it myself everytime?

Is there a way to make the player, only use one instance of itself? kind of like in PotPlayer, were if i were to open 1 video meanwhile already having one playing it will not open up on a new instance of a player.

I understand that you are not the one who made MPV and only the GUI, but i wanted to ask here before i asked them.

**Comment by u8sand** [comment]
In terms of the cmd window--that's a compilation issue which should be fixed along with all the other compilation issues as well as fontconfig issues. It's mostly a question of finding a working build system (we think msys2 is it).

We could use multiple instances of the library internally but it's not currently set up to do that and I don't see any real benefit to it because most of us don't watch multiple videos at one time.

**Comment by dragons4life** [comment]
<blockquote>We could use multiple instances of the library internally but it's not currently set up to do that and I don't see any real benefit to it because most of us don't watch multiple videos at one time.</blockquote>
Well yeah that's what i was trying to say, that i only wanted one instance of the player being used, not open another one when i open another video? unless i misread what you typed.

1. MPV is open playing certain video
2. Open another Video
3. MPV opens another instance/window of itself with the video i just opened, but the other one is still open and running again.

Simply want to make the MPV to open all future Video files within the first player without making another one.

**Comment by amazingfate** [comment]
If you want to open another file in the same window, ctrl+o to select a file and it will be played in the current window. If you click the file in a file manager, it will open a new window. I think this design doesn't have any problems.

**Comment by dragons4life** [comment]
It's not really the design of it, it's the option to choose not to.

Also i know you can open up files like that, but if i am using "livestreamer" to watch twitch and when i want to switch to another streamer, another player comes up with another black window.

However i don't think the problem is his fault, it probably is mpv.

**Comment by godly-devotion** [comment]
@dragons4life this is a preview build of Baka that has this fixed. you can use this build until we can get static compilation working. Download: https://db.tt/cwPmrHMw

**Comment by u8sand** [comment]
The black window was fixed; see https://github.com/u8sand/Baka-MPlayer/issues/74

I'll have to try out baka with livestreamer--will investigate this bug after our release.

**Comment by godly-devotion** [comment]
@dragons4life The cmd window popping up has been officially fixed with latest version (2.0.3).

@u8sand Basically he wants to be able to have a "single-instance mode" where if he already has Baka open and he opens another file via File Explorer, it doesn't create a new window, but replaces the loaded file in the already open Baka instance.

**Comment by godly-devotion** [comment]
We've discussed about the "single-instance mode" feature and found it to be not that useful. However if there is more demand in the future, we may consider it.
Thanks for your suggestion.
