### ISSUE TITLE
Option to hide all window decoration

### ISSUE THREAD

**Issue by alexzeitgeist** [u8sand/Baka-MPlayer#158]
It would be nice if there was an option to hide all controls in windowed mode and only show the actual video. This way valuable screen estate can be saved when you watch in windowed mode.

**Comment by u8sand** [comment]
@alexzeitgeist do you suggest the fullscreen window's functionality without being fullscreen? (with hovering responses and all)

**Comment by alexzeitgeist** [comment]
@u8sand exactly. Basically windowed mode without any decoration. mpv does it with --no-border to  disable the standard window decorations (or border=no in config files).

**Comment by u8sand** [comment]
@alexzeitgeist I've successfully implemented this in the other branch but there are a few things that need to be fixed.

1. I called it "windowed" which is horrible, not sure what to call it
2. the auto-hide playlist works very strangely, how SHOULD it work?

To test this, checkout the windowed-fullscreen branch and add to your bakamplayer.ini-> `"windowed": true`.

Please see if you can test this out and give me some feedback so that I can finalize this feature.

**Comment by alexzeitgeist** [comment]
@u8sand, congrats, that was fast.

1. How about any of the following: "borderless", "borderless windowed", "no decorations",  "no window decorations"

2. I'll check it out as soon as I find some time.

Cheers,
