### ISSUE TITLE
Current item on Playlist illegible due to text color.

### ISSUE THREAD

**Issue by ConundrumAdInfinitum** [u8sand/Baka-MPlayer#175]
Baka MPlayer version 2.04 64bit Windows:

With this version of the player I notice what appears to be an error...

While playing video, if the Playlist is open, the Current title's filename/title is in Black text, not White (or the intended color of) text. This unfortunately makes the title illegible.

**Comment by godly-devotion** [comment]
This bug has been fixed in cb42b76. You can redownload Baka MPlayer from our website to get the fixed build.
What happened was that we initially released 2.0.4 with this bug. After noticing the bug and fixing it, we updated the builds on the website (and GitHub) to so that the fix was incorporated into it.
