### ISSUE TITLE
Mouse gestures doesn't work

### ISSUE THREAD

**Issue by suhr** [u8sand/Baka-MPlayer#222]
When you hold the mouse button, mouse cursor turns to hand, but when you move it, it turns back to arrow and nothing happens.

Qt version: 5.8.0

**Comment by wb9688** [comment]
It works fine for me…

**Comment by suhr** [comment]
I'm using git version of baka-mplayer.

**Comment by u8sand** [comment]
Are you using any unique windows manager and you have gestures enabled in
preferences correct? (The other gesture function is to move your window
around)

**Comment by suhr** [comment]
Indeed, if I unmaximize the window, gestures drag it.
How do I return old behaviour? I can you wm to move my windows and I don't need a special option for it.

**Comment by u8sand** [comment]
In preferences you should find a checkbox to enable the vdrag hdrag gesture
functionality.

On Aug 7, 2016 11:08 AM, "Сухарик" <notifications@github.com> wrote:

Indeed, if I unmaximize the window, gestures drag it.
How do I return old behaviour? I can you wm to move my windows and I don't
need a special option for it.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/u8sand/Baka-MPlayer/issues/222#issuecomment-238087741>,
or mute the thread

**Comment by suhr** [comment]
I can't find it. There's only `Use Mouse & Touch Gestures`.

**Comment by u8sand** [comment]
That's the one, have you checked it?

**Comment by suhr** [comment]
Yes. If I disable it, nothing changes.

**Comment by suhr** [comment]
If I hold <kbd>Ctrl</kbd>, I can actually use mouse gestures. But I want to be able to use them without holding <kbd>Ctrl</kbd>.

**Comment by u8sand** [comment]
So baka doesn't look for the control modifier. I'm thinking it has something to do with your wm. Which wm are you using? It almost sounds as if baka isn't getting the mouse move event--i could see it affecting hover but it should certainly work while being clicked..

**Comment by suhr** [comment]
i3wm.

**Comment by godly-devotion** [comment]
Everything will be fixed in the next incarnation :D

**Comment by u8sand** [comment]
I use i3wm as well but I have no issues with gestures (whether in floating or tiling layouts); can you confirm that you're still having issues?
