### ISSUE TITLE
Player's seekbar is not working

### ISSUE THREAD

**Issue by rahmanshaber** [u8sand/Baka-MPlayer#265]
i am in Linux(ARCH)
when i put mouse in seekbar and go to a time ,it dose not go to that time.
instead of going the time i selected it plays the video from first.

is there any way to install only the libmpv or required library with the player.when i compile .pro file it will also compile livmpv and other library.all in one.
i don't want two player in my system. 1.mpv 2.Baka-mplayer.

**Comment by u8sand** [comment]
Fundamentally, baka uses libmpv as a dependency; the mpv binary could be
removed but there isn't much point as the bulk of the player is still in
the required libmpv.

Our project does not compile either mpv or libmpv though I have compilation
instructions for libmpv which compile both at the same time.

Which distribution of Linux are you on?

On Nov 17, 2017 3:02 AM, "rahmanshaber" <notifications@github.com> wrote:

i am in linux.
when i put mouse in seekbar and go to a time ,it dose not go to that time.
instead of going the time i selected it plays the video from first.

is there any way to install only the libmpv or required library with the
player.when i compile .pro file it will also compile livmpv and other
library.all in one.
i don't want two player in my system. 1.mpv 2.Baka-mplayer.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/u8sand/Baka-MPlayer/issues/265>, or mute the thread

**Comment by rahmanshaber** [comment]
in arch there is no libmpv-dev as it is a "rolling release"(manjaro team said).when i install baka it also install full mpv player with gui.
so i am telling that if u include the libmpv in baka source it should be good for compiling and reduce the defeculties .
if i include libmpv from there github page i don't think it will compile it with baka.as i don'k know how to do it properly.
I don't like the mpv. But there is no way i can remove it and use baka. iIn arch baka installs full mpv as depedence.
So i request u please made baka a standalone player.(by including libmpv and other file in github repo and include the in cmake file .So when i do cmake ,i will not show it needs whole mpv
It's GUI and one feature (when i open a file ,it auto include all the files in the folder in the play-list) make me use it.
thanks

**Comment by loathingKernel** [comment]
Yes please, and include Qt while you are at it too, I don't like having a whole UI installed only for baka. Maybe pulseaudio and ffmpeg too. How about the kernel? Would that be viable?

**Comment by u8sand** [comment]
@rahmanshaber 
Many applications on Windows behave like this, including all of the necessary dependencies with the package, mainly by compiling statically. It defeats the operating system ability to share resources and increases the amount of storage and RAM usage on your system, this is why linux packages things differently. I'm not a package maintainer, I only write the source, so really this is something you need to ask the maintainers of the baka-mplayer package in the repository of your distribution. 

Having a libmpv-dev because of "rolling release" was an answer to a different question--packaging of libmpv-dev outside of mpv itself could happen if they wanted it to. The reason they were confused is because any-dev doesn't make sense on rolling release as it's already dev. It'd probably just be called libmpv instead of mpv because it provides libmpv and not mpv.

@loathingKernel 
If you truly want everything packed into a single binary, you need to compile Baka statically. This involves adding the CONFIG+=static flag to the qmake process ***and*** compiling mpv and qt and all of their dependencies from source statically. It will probably be very difficult because most people _don't_ compile things statically because as stated before, it isn't efficient.


I'm sorry I can't do the things you want--I understand baka is getting out of date but it just isn't a priority for me. These issues arise because mpv updates and baka doesn't and sometimes mpv makes breaking changes. Putting binaries in a source repository is not something anyone should ever do.

**Comment by loathingKernel** [comment]
@u8sand Thank you for the serious answer, I was just joking, as I find the request above really out of place.

**Comment by u8sand** [comment]
@loathingKernel I had a feeling **you** were joking about the kernel but figured pulling all of qt for baka when you don't use qt could be a legitimate concern.

I actually use ArchLinux myself, wasn't sure if Manjarin uses a different set of repositories maintained by someone else. Thanks for the clarification :+1:

**Comment by mindbound** [comment]
I can confirm that seekbar is not working (clicking on it doesn't skip video to the desired position but instead restarts playback). Baka v2.0.4, Arch Linux x64, mpv v0.27.2.

**Comment by Logmytech** [comment]
Same issue for me.

Playback begins from the start when one seeks using seekbar.

Manjaro Linux Stable.

**Comment by u8sand** [comment]
This was fixed ages ago but never made it into an "official release". Please build from the master branch / use the AUR on ArchLinux.
