### ISSUE TITLE
Compile for windows without console

### ISSUE THREAD

**Issue by u8sand** [u8sand/Baka-MPlayer#74]
Though this should be very simple--I've spent much too long to no avail. If someone has any clue as to what might be the problem please share.

I've tried #mingw and #qt and searching through the internet. Here are some solutions that DON'T work.

- Adding `-mwindows` to linker flags
- Adding ` -Wl,-subsystem,windows`
- Adding (as suggested by http://blog.debao.me/2013/07/link-confilict-between-sdl-and-qt-under-windows/ ; the article makes sense and the source code agrees. It doesn't work though.)

        win32:QMAKE_LIBS_QT_ENGTRY -= -lqtmain
        win32-g++:DEFINES -= QT_NEEDS_QMAIN
  or

        CONFIG-= windows
        QMAKE_LFLAGS += $$QMAKE_LFLAGS_WINDOWS
  or both
- Adding `CONFIG-=console` or `CONFIG+=windows` (which is already there so why would it work)

and more...

I'm unsure as to whether this is a qt problem or an mxe problem (or perhaps my own? I don't see any terminal on Linux though..)

I wouldn't mind handling the calling of WinMain/SDL_main myself if only I knew how to disable the existing things. (No calling it after using the `DEFINES -= QT_NEEDS_QMAIN` above didn't work)

I do hope this problem is solved eventually--the current solution is disgusting, that-is calling `FreeConsole` on startup (resulting in a flashed console).

**Comment by amazingfate** [comment]
this seems to be the problem of mingw.
shall we try msvs to build the windows release?

**Comment by u8sand** [comment]
If someone can get that to work. I had a very difficult time just getting mingw to work harhar.

Another thing to try is to get it to work with the Microsoft compilers. The difficulty there however is compiling all the mpv dependencies (and mpv) on it too.

**Comment by amazingfate** [comment]
As it is said in http://blog.debao.me/2013/07/link-confilict-between-sdl-and-qt-under-windows/, this is a problem caused by "Link Confilict Between SDL and Qt", and SDL.h is included. 
If I only use "CONFIG += windows", it failed to build with error:

/home/liujianfeng/baka-win/mxe.x86_64/usr/x86_64-w64-mingw32.static/lib/../lib/libSDLmain.a(SDL_win32_main.o): In function `console_main':
/home/liujianfeng/baka-win/mxe.x86_64/tmp-sdl-x86_64-w64-mingw32.static/SDL-1.2.15/./src/main/win32/SDL_win32_main.c:315: undefined reference to `SDL_main'
collect2: error: ld returned 1 exit status

But as I know we don't use SDL.h, maybe that's the problem?

**Comment by u8sand** [comment]
As stated in my post--i've seen and tried those things. I was
unsuccessful--if you can figure out a way it'd be enormously appreciated.

We need both SDL and Qt--both want to provide their own mains so you don't
need WinMain.  I've tried various mascaraded #defines to get this to work
to no avail.

**Comment by amazingfate** [comment]
@u8sand if I add 
```
#include <SDL.h>
```
to the main.cpp, it can be loaded only if I add 
```
PKGCONFIG += sdl
```
to the .pro file.
It seems that 
```
DEFINES -= QT_NEEDS_QMAIN
```
just prevent to use sdl.

**Comment by u8sand** [comment]
I rebuilt mxe toolchain today and it fixed itself.
