### ISSUE TITLE
Name

### ISSUE THREAD

**Issue by maimteve** [u8sand/Baka-MPlayer#92]
I've seen some opposition to the name "baka-MPlayer". Some think this means the player is just for anime. Others find the name nerdy and cringy. It's similar opposition that I've found to the "Kawaii Codec Pack". People won't use it simply because they hate anime. Never underestimate the immaturity of nerds. 

There should be a new name, one which is not anime themed.

**Comment by u8sand** [comment]
I have no particular attachment to the name; I would be very keen on receiving some suggestions for a new name which appeals to everyone.

A Gnome is a pagan Alchemist--I don't believe that has chased away people with religious beliefs from using Gnome.
Google is a number--I don't believe that has chased away people who aren't nerds/deal with numbers.

My point is a name is a name--I find it ridiculous that people find such useless things to complain about. Facebook sounds stupid, so does twitter. If you have a good product I don't think it matters.

But that's just my rant on the subject, again I'm up to anything.

**Comment by DesuDesuDesuDesu** [comment]
>Some think this means the player is just for anime. Others find the name nerdy and cringy. ... There should be a new name, one which is not anime themed.

baka! the name's totally subarashii and sugoi desu.

**Comment by godly-devotion** [comment]
Either way I have a new name in mind. However I may change it if I find a better name.

**Comment by ConundrumAdInfinitum** [comment]
A couple of simple names ideas that may fit could be:

Reel (as it pertains to movies shown with a reel of film)

Screen or Screentime (as it pertains to sitting down and taking in a movie from a projection source on a projection screen)

Couldn't help throwing a couple of suggestions out there for you, I'm kind-of a word-nerd.

Zoom (as it is based on an optical lens term, also relates to fast and light and quick, as it pertains to its new, zippy, libmpv-based engine to provide the movie viewing goods)

**Comment by ConundrumAdInfinitum** [comment]
Apologies on suggesting Zoom, apparently in-use by In matrix.com for a video player product already.

Screen, Screentime/ScreenTime, Reel and ReelTime, are however, not in use currently.

ReelTime is kind of cute, as it implies what the purpose of the app is for (if this was the new name); watching movies, and what you'd be doing while using it: watching movies... Because it's "reel time".

**Comment by godly-devotion** [comment]
@ConundrumAdInfinitum I like the direction in where the names are going. However ReelTime sounds a bit similar to the god-awful RealPlayer. Also in the future, we are planning to add social interaction support (ie. comments), and are thinking of gearing the name towards that idea.

**Comment by ConundrumAdInfinitum** [comment]
So, something more along the lines of CinemaRundown or CinemaSuggest?


Sent from my T-Mobile 4G LTE Device

<div>-------- Original message --------</div><div>From: Joshua Park <notifications@github.com> </div><div>Date:02/06/2015  6:13 PM  (GMT-08:00) </div><div>To: u8sand/Baka-MPlayer <Baka-MPlayer@noreply.github.com> </div><div>Cc: ConundrumAdInfinitum <lch.three@gmail.com> </div><div>Subject: Re: [Baka-MPlayer] Name (#92) </div><div>
</div>@ConundrumAdInfinitum I like the direction in where the names are going. However ReelTime sounds a bit similar to the god-awful RealPlayer. Also in the future, we are planning to add social interaction support (ie. comments), and are thinking of gearing the name towards that idea.

**Comment by ConundrumAdInfinitum** [comment]
Maybe "Featured" as it could refer to playing features and discussing/recommending Features (as in films or anime), and possibly rating them.

Are you guys planning an "IMDB-alike" module?

Or more like a Netflix-Facebook recommendation bridge thingy?


Sent from my T-Mobile 4G LTE Device

<div>-------- Original message --------</div><div>From: Joshua Park <notifications@github.com> </div><div>Date:02/06/2015  6:13 PM  (GMT-08:00) </div><div>To: u8sand/Baka-MPlayer <Baka-MPlayer@noreply.github.com> </div><div>Cc: ConundrumAdInfinitum <lch.three@gmail.com> </div><div>Subject: Re: [Baka-MPlayer] Name (#92) </div><div>
</div>@ConundrumAdInfinitum I like the direction in where the names are going. However ReelTime sounds a bit similar to the god-awful RealPlayer. Also in the future, we are planning to add social interaction support (ie. comments), and are thinking of gearing the name towards that idea.

**Comment by amazingfate** [comment]
Nobody has said baka is related to anime. It is just a name just as @u8sand said. If you read the wikipedia: http://ja.wikipedia.org/wiki/%E9%A6%AC%E9%B9%BF, you will find baka is just a Japanese word. It is used not only in anime. It has both positive and negative meanings.

**Comment by maimteve** [comment]
My thinking:

>KISS
>don't be overly cute

My suggestion: bg-mplayer. With "BG" not really standing for anything. I got the idea from "baka gaijin".

**Comment by suhr** [comment]
> bg-mplayer
bmpv.

**Comment by u8sand** [comment]
I like the short name. What do you think @godly-devotion ?

**Comment by godly-devotion** [comment]
I liked `acai`/`acai-player` player :(
If we can't think of something else, bmpv it is.

**Comment by godly-devotion** [comment]
Also one thing I would like to mention is that the name should arouse interest into the player. For example, Baka MPlayer has an "interesting name" so that it pops out from the never ending list of media players on popular download websites. Technically speaking, bmpv is great cause its short and makes sense. However, people that are not technically inclined might be deterred from its unusual name.

**Comment by ConundrumAdInfinitum** [comment]
What about ICU (Internet Content Utility)?

If the player: 

Plays video
Gets a YouTube module
Gets a chat/rating/reccomend module

The name would be short as an acronym, and expand to describe what it does.


Sent from my T-Mobile 4G LTE Device

<div>-------- Original message --------</div><div>From: Joshua Park <notifications@github.com> </div><div>Date:02/07/2015  2:57 PM  (GMT-08:00) </div><div>To: u8sand/Baka-MPlayer <Baka-MPlayer@noreply.github.com> </div><div>Cc: ConundrumAdInfinitum <lch.three@gmail.com> </div><div>Subject: Re: [Baka-MPlayer] Name (#92) </div><div>
</div>Also one thing I would like to mention is that the name should arouse interest into the player. For example, Baka MPlayer has an "interesting name" so that it pops out from the never ending list of media players on popular download websites. Technically speaking, bmpv is great cause its short and makes sense. However, people that are not technically inclined might be deterred from its unusual name.

**Comment by jmdavis** [comment]
Personally, if I had a problem with the name baka-mplayer, it would be that it has mplayer in its name when it uses mpv, not mplayer (though it wouldn't surprise me if more people found it thanks to mplayer being in the name and them looking for something related to mplayer, particularly when mpv is so much newer than mplayer). The fact that it has baka in its name doesn't bother me at all, though if I were going with baka, I'd have gone with baka-mpv, because it uses mpv.

Ideally, a name would be unique, memorable, and recognizable for what it is. Having mplayer or mpv in the name helps make it recognizable, and baka is pretty unique and memorable as far as video players go. I'd say that you should just pick a name that you like and go with it. If some folks don't like the name, then oh well. You'll never please everyone. Honestly, though, if anyone thinks that a video player is just for anime (even if it's named anime-player), then they don't know much about video players, and I wouldn't count their opinion for much. I'd probably just leave it as-is though, since changing it will just reduce its name recognition in the short term, and unless the new name is way better than baka-mplayer, it probably wouldn't make much of a difference in the long term.

But I'm not one of the developers on this project, and I don't care all that much about the name as long as it it does its job.

**Comment by ConundrumAdInfinitum** [comment]
I agree with Jonathan M Davis, I never really had much of a problem with
baka-mplayer as a name myself. I was suggesting names to be helpful.

Since there is some potential confusion around the "mplayer" part of
baka-mplayer,

Why not just baka-mpv? or mpv-player?

Both are simple, indicate that the player uses mpv as the "rendering
engine", and is a little bit more than using mpv standalone.

Also, it isn't overly cute, as another put it.

On Wed, Feb 11, 2015 at 11:50 PM, Jonathan M Davis <notifications@github.com

**Comment by maimteve** [comment]
I like the idea of using mpv intstead of mplayer. 

How about b-mpv?

**Comment by robin007bond** [comment]
I have no problems with the name, except the "mplayer" part, since Baka-Mplayer uses libmpv.

**Comment by godly-devotion** [comment]
@amazingfate what do you think about `mao-player` (猫)? i thought about `neko-player` but neko is kind of ubiquitous and maybe unoriginal.

**Comment by robin007bond** [comment]
Mao reminds me of Mao Zedong. :cry:

**Comment by amazingfate** [comment]
"mao" doesn't only mean "猫" in Chinese, I think "miao"(喵) is better if you wanna something with cat.

**Comment by godly-devotion** [comment]
A friend of mine recommended me the name `fovea`. Put simply, it is the part of the eye that is responsible for sharp central vision. I've also sketched out a prototype logo if you want to see https://db.tt/vzJ7Rwdo/ (I've found out that it looks similar to the cbs logo after creating it).

Thoughts?

**Comment by DesuDesuDesuDesu** [comment]
Ahoy,
first of all: I'd also definitly rename the "mplayer" part to "mpv" - that's not confusing as it is, but deceptive. There's a trusted german website about computer stuff, even they write that the player "is based on MPlayer" [>>](http://www.chip.de/downloads/Baka-MPlayer_62165856.html).
About "Fovea": I like the idea, it's witty. It's kind of an inside joke because most people won't get it; but the proposed logo also is a nice hint. It also sounds interesting (especially concerning the people who won't get it). I don't know if the similarity to CBS is a problem - as an not-US-american (=~half of your target group), I've never seen their logo before. I guess the triangle is difference enough. The logo looks cool!
Personally, I'd (still) prefer "Baka MPV", but it's not really that important to me an already-user.

btw: Markdown, wtf. Why can't i just write [url=x]y[/url] here desu~

**Comment by u8sand** [comment]
@DesuDesuDesuDesu markdown: use `<http://thisurl.com>` or `[This](url)`

Thank you for all your contributions to the purpose; but I still have yet to find a name I'm eager to adopt.

**Comment by godly-devotion** [comment]
Hey folks! You probably thought we weren't thinking of a new name right? Well I'm extremely please to announce the new name of our media player.

`mochi-player`

We sincerely thank everyone of you for your suggestions and recommendations that brought us here today.

**Comment by amazingfate** [comment]
Does mochi means this: https://ja.wikipedia.org/wiki/%E9%A4%85 ?

**Comment by godly-devotion** [comment]
@amazingfate Yeah.  But usually they are made into a colorful round shape to make it look tastier. Personally I love mochi ice cream.

**Comment by ConundrumAdInfinitum** [comment]
Naming it after food when it's got nothing to do with food.... *scratches
head*

At least Baka-MPlayer lets you know it's an MPlayer derivative (yes, mpv,
the spiritual successor to MPlayer).

Just a thought
